<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="xmlTree.xsl"?>
<!DOCTYPE note [
<!ELEMENT tree (branch+)>
<!ELEMENT branch (branchText,(branch|leaf)*)>
<!ATTLIST branch id CDATA #REQUIRED>
<!ATTLIST branch branchLink CDATA #REQUIRED>
<!ATTLIST branch baseX CDATA #REQUIRED>
<!ATTLIST branch baseY CDATA #REQUIRED>
<!ELEMENT branchText (#PCDATA)>
<!ELEMENT leaf (leafText,link,baseX,baseY)>
<!ELEMENT leafText (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT baseX (#PCDATA)>
<!ELEMENT baseY (#PCDATA)>
]>
<tree>
	<branch id="UCM" branchLink="notRedirect" baseX="0" baseY="0">
		<branchText>UCM</branchText>
	</branch>
	<branch id="GRL" branchLink="notRedirect" baseX="0" baseY="0">
		<branchText>GRL</branchText>
	</branch>
<branch baseX="0" baseY="0" branchLink="notRedirect" id="DEF">
<branchText>Definitions</branchText>
<leaf><leafText>UCM Definitions</leafText><link>UCM_Definitions.html</link><baseX>215</baseX><baseY>2</baseY></leaf>
<leaf><leafText>GRL Definitions</leafText><link>GRL_Definitions.html</link><baseX>215</baseX><baseY>2</baseY></leaf>
<leaf>
		<leafText>UCM Scenarios</leafText>
		<link>UCM_Scenarios.html</link>
		<baseX>215</baseX>
		<baseY>2</baseY></leaf><leaf><leafText>Title Page</leafText><link>main.html</link><baseX>215</baseX><baseY>2</baseY></leaf>
	
</branch> 
</tree>
